apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: o7g7k0p87-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/o7g7k0p87-dotnet-basic-gitops