apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o7g7k0p87-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:5f3bbe24c4846f2a0c42d5baba352e1a3bffae2b@sha256:a6172ce7ca6bb0d10325e7c0dce8c773769e972e2ca6479abba68dc05e7d36cd
          name: container-image
