apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o7g7k0p87-dotnet-basic
  janus-idp.io/tekton: o7g7k0p87-dotnet-basic
  backstage.io/kubernetes-id: o7g7k0p87-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o7g7k0p87-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
